### ISSUE TITLE
Where are the sound files stored?

### ISSUE THREAD

**Issue by asktoby** [Rectus/destinations_range#1]
Hello, I'm trying to make my own VR Home Environment. If I may ask a question:
Your file
ski_slope2/scripts/soundscapes_ski_slope.txt
refers to 
"sounds/diagnostics/wind_light_foliage_lp_01.vsnd"
but I cannot see any /sounds directory nor *.vsnd files in your repository.
Where are these audio files stored please?

**Comment by Rectus** [comment]
That particular file is an old entry from the Destinations version of the map I left in there by mistake. 

Sound files in general are stored as compiled .vsnd_c files under the game directory, and any source files are added under the content directory as wav or .mp3 files. The actual .vsnd files are virtual files that don't actually exist in the directory structure. The engines virtual file system uses that name to find the corresponding .vsnd_c file to play. 

I haven't included any sound files in the repository. If you want the compiled versions, you'll have to extract them from the workshop files. See the instructions in the readme for that.
